---
abstract: The great new TCPIP::Tap!
author:
  - 'Ben AVELING <bena.aveling at optusnet.com.au>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TCPIP-Tap
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006
version: 0.01
